executor: docker-env-go-test-remote-docker
parallelism: 8
steps:
  - exit-if-ui-or-docs-branch
  - checkout
  - setup_remote_docker:
      version: 20.10.17
      docker_layer_caching: true
  - go_test:
      log_dir: "/tmp/testlogs"
      use_docker: true
  - store_artifacts:
      path: test-results
  - store_test_results:
      path: test-results
  - store_artifacts:
      path: "/tmp/testlogs"
