steps:
  - add_ssh_keys:
      fingerprints:
        # "CircleCI Additional SSH Key" associated with hc-github-team-secure-vault-core GitHub user
        - "b8:e2:38:f8:5b:1b:82:f3:1f:23:fa:46:6e:95:e7:e9"
  - run: |
      git config --global url."git@github.com:".insteadOf https://github.com/
