name: enos-verify-stable

on:
  repository_dispatch:
    types:
      - enos-verify-stable
      - enos-verify-stable::*

jobs:
  enos-verify-stable:
    name: Enos verify stable artifact
    if: ${{ startsWith(github.event.client_payload.payload.branch, 'release/') }}
    uses: ./.github/workflows/enos-run.yml
    with:
      artifact-source: artifactory
      artifact-name: ${{ github.event.client_payload.payload.product }}_${{ github.event.client_payload.payload.version }}_linux_amd64.zip
      artifact-revision: ${{ github.event.client_payload.payload.sha }}
      artifact-version: ${{ github.event.client_payload.payload.version }}
    secrets: inherit
